# Generated by Django 5.2.4 on 2025-07-12 07:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_initial'),
        ('questions', '0003_alter_question_options_question_bounty_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-is_accepted', '-votes', '-created_at'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AddField(
            model_name='answer',
            name='edit_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this answer has been edited'),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this record is active'),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is marked as deleted but not removed from database'),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_edited',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this answer has been edited'),
        ),
        migrations.AddField(
            model_name='answer',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, help_text='When this answer was last edited', null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(help_text='User who provided the answer', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(help_text='Answer content/body'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_accepted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this answer is accepted as the best answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='Question this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(db_index=True, default=0, help_text='Net vote count (upvotes - downvotes)'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='answers_questio_3d2018_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['author'], name='answers_author__068af8_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_accepted'], name='answers_is_acce_dd830d_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['votes'], name='answers_votes_30997e_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_edited'], name='answers_is_edit_99760e_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'is_accepted'], name='answers_questio_dafd07_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'votes'], name='answers_questio_8d3e14_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['author', 'created_at'], name='answers_author__22ca92_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['votes', 'created_at'], name='answers_votes_6d9f73_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_active', 'is_accepted'], name='answers_is_acti_9f2546_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_active', 'question'], name='answers_is_acti_4842e4_idx'),
        ),
    ]
