# Generated by Django 5.2.4 on 2025-07-12 07:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_alter_answer_options_answer_edit_count_and_more'),
        ('notifications', '0002_initial'),
        ('questions', '0003_alter_question_options_question_bounty_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, help_text='URL to navigate to when notification is clicked'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this record is active'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is marked as deleted but not removed from database'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_important',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this is an important notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='When the notification was read', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the notification has been read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(help_text='Notification message content'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('answer', 'New Answer'), ('vote', 'Vote'), ('accept', 'Answer Accepted'), ('comment', 'Comment'), ('mention', 'Mention'), ('bounty', 'Bounty'), ('moderation', 'Moderation'), ('system', 'System')], db_index=True, help_text='Type of notification', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_answer',
            field=models.ForeignKey(blank=True, help_text='Related answer (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='answers.answer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_question',
            field=models.ForeignKey(blank=True, help_text='Related question (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='User who triggered the notification (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='Notification title', max_length=255),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient'], name='notificatio_recipie_1dd18d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sender'], name='notificatio_sender__893501_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_important'], name='notificatio_is_impo_8e1cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_question'], name='notificatio_related_ac0e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_answer'], name='notificatio_related_e08493_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'notification_type'], name='notificatio_recipie_b1a229_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_2c3905_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', 'created_at'], name='notificatio_is_read_9b69ad_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_important', 'created_at'], name='notificatio_is_impo_d42140_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_active', 'is_read'], name='notificatio_is_acti_85d8e4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_active', 'recipient'], name='notificatio_is_acti_9a21d0_idx'),
        ),
    ]
